// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/dominodatalab/hephaestus/pkg/api/hephaestus/v1"
	hephaestusv1 "github.com/dominodatalab/hephaestus/pkg/clientset/typed/hephaestus/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeImageBuilds implements ImageBuildInterface
type fakeImageBuilds struct {
	*gentype.FakeClientWithList[*v1.ImageBuild, *v1.ImageBuildList]
	Fake *FakeHephaestusV1
}

func newFakeImageBuilds(fake *FakeHephaestusV1, namespace string) hephaestusv1.ImageBuildInterface {
	return &fakeImageBuilds{
		gentype.NewFakeClientWithList[*v1.ImageBuild, *v1.ImageBuildList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("imagebuilds"),
			v1.SchemeGroupVersion.WithKind("ImageBuild"),
			func() *v1.ImageBuild { return &v1.ImageBuild{} },
			func() *v1.ImageBuildList { return &v1.ImageBuildList{} },
			func(dst, src *v1.ImageBuildList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ImageBuildList) []*v1.ImageBuild { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ImageBuildList, items []*v1.ImageBuild) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
