// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	hephaestusv1 "github.com/dominodatalab/hephaestus/pkg/api/hephaestus/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImageCaches implements ImageCacheInterface
type FakeImageCaches struct {
	Fake *FakeHephaestusV1
	ns   string
}

var imagecachesResource = schema.GroupVersionResource{Group: "hephaestus", Version: "v1", Resource: "imagecaches"}

var imagecachesKind = schema.GroupVersionKind{Group: "hephaestus", Version: "v1", Kind: "ImageCache"}

// Get takes name of the imageCache, and returns the corresponding imageCache object, and an error if there is any.
func (c *FakeImageCaches) Get(ctx context.Context, name string, options v1.GetOptions) (result *hephaestusv1.ImageCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(imagecachesResource, c.ns, name), &hephaestusv1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hephaestusv1.ImageCache), err
}

// List takes label and field selectors, and returns the list of ImageCaches that match those selectors.
func (c *FakeImageCaches) List(ctx context.Context, opts v1.ListOptions) (result *hephaestusv1.ImageCacheList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(imagecachesResource, imagecachesKind, c.ns, opts), &hephaestusv1.ImageCacheList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hephaestusv1.ImageCacheList{ListMeta: obj.(*hephaestusv1.ImageCacheList).ListMeta}
	for _, item := range obj.(*hephaestusv1.ImageCacheList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imageCaches.
func (c *FakeImageCaches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(imagecachesResource, c.ns, opts))

}

// Create takes the representation of a imageCache and creates it.  Returns the server's representation of the imageCache, and an error, if there is any.
func (c *FakeImageCaches) Create(ctx context.Context, imageCache *hephaestusv1.ImageCache, opts v1.CreateOptions) (result *hephaestusv1.ImageCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(imagecachesResource, c.ns, imageCache), &hephaestusv1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hephaestusv1.ImageCache), err
}

// Update takes the representation of a imageCache and updates it. Returns the server's representation of the imageCache, and an error, if there is any.
func (c *FakeImageCaches) Update(ctx context.Context, imageCache *hephaestusv1.ImageCache, opts v1.UpdateOptions) (result *hephaestusv1.ImageCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(imagecachesResource, c.ns, imageCache), &hephaestusv1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hephaestusv1.ImageCache), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeImageCaches) UpdateStatus(ctx context.Context, imageCache *hephaestusv1.ImageCache, opts v1.UpdateOptions) (*hephaestusv1.ImageCache, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(imagecachesResource, "status", c.ns, imageCache), &hephaestusv1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hephaestusv1.ImageCache), err
}

// Delete takes name of the imageCache and deletes it. Returns an error if one occurs.
func (c *FakeImageCaches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(imagecachesResource, c.ns, name, opts), &hephaestusv1.ImageCache{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImageCaches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(imagecachesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &hephaestusv1.ImageCacheList{})
	return err
}

// Patch applies the patch and returns the patched imageCache.
func (c *FakeImageCaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hephaestusv1.ImageCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(imagecachesResource, c.ns, name, pt, data, subresources...), &hephaestusv1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hephaestusv1.ImageCache), err
}
