// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/dominodatalab/hephaestus/pkg/api/hephaestus/v1"
	hephaestusv1 "github.com/dominodatalab/hephaestus/pkg/clientset/typed/hephaestus/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeImageCaches implements ImageCacheInterface
type fakeImageCaches struct {
	*gentype.FakeClientWithList[*v1.ImageCache, *v1.ImageCacheList]
	Fake *FakeHephaestusV1
}

func newFakeImageCaches(fake *FakeHephaestusV1, namespace string) hephaestusv1.ImageCacheInterface {
	return &fakeImageCaches{
		gentype.NewFakeClientWithList[*v1.ImageCache, *v1.ImageCacheList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("imagecaches"),
			v1.SchemeGroupVersion.WithKind("ImageCache"),
			func() *v1.ImageCache { return &v1.ImageCache{} },
			func() *v1.ImageCacheList { return &v1.ImageCacheList{} },
			func(dst, src *v1.ImageCacheList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ImageCacheList) []*v1.ImageCache { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ImageCacheList, items []*v1.ImageCache) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
