# Source: hephaestus/templates/crd-hooks.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dominodatalab:controller:hephaestus
  labels:
    app.kubernetes.io/name: hephaestus
    helm.sh/chart: hephaestus-0.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dominodatalab:controller:release-name-hephaestus:hook
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
