// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	hephaestusv1 "github.com/dominodatalab/hephaestus/pkg/api/hephaestus/v1"
	scheme "github.com/dominodatalab/hephaestus/pkg/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ImageCachesGetter has a method to return a ImageCacheInterface.
// A group's client should implement this interface.
type ImageCachesGetter interface {
	ImageCaches(namespace string) ImageCacheInterface
}

// ImageCacheInterface has methods to work with ImageCache resources.
type ImageCacheInterface interface {
	Create(ctx context.Context, imageCache *hephaestusv1.ImageCache, opts metav1.CreateOptions) (*hephaestusv1.ImageCache, error)
	Update(ctx context.Context, imageCache *hephaestusv1.ImageCache, opts metav1.UpdateOptions) (*hephaestusv1.ImageCache, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, imageCache *hephaestusv1.ImageCache, opts metav1.UpdateOptions) (*hephaestusv1.ImageCache, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*hephaestusv1.ImageCache, error)
	List(ctx context.Context, opts metav1.ListOptions) (*hephaestusv1.ImageCacheList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *hephaestusv1.ImageCache, err error)
	ImageCacheExpansion
}

// imageCaches implements ImageCacheInterface
type imageCaches struct {
	*gentype.ClientWithList[*hephaestusv1.ImageCache, *hephaestusv1.ImageCacheList]
}

// newImageCaches returns a ImageCaches
func newImageCaches(c *HephaestusV1Client, namespace string) *imageCaches {
	return &imageCaches{
		gentype.NewClientWithList[*hephaestusv1.ImageCache, *hephaestusv1.ImageCacheList](
			"imagecaches",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *hephaestusv1.ImageCache { return &hephaestusv1.ImageCache{} },
			func() *hephaestusv1.ImageCacheList { return &hephaestusv1.ImageCacheList{} },
		),
	}
}
