repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: golangci-lint
        args: ["run", "./..."]
        language: golang
        pass_filenames:  false
      - id: build
        name: build
        entry: make
        args: ["build"]
        language: golang
        pass_filenames: false
      - id: test
        name: test
        entry: make
        args: ["test"]
        language: golang
        pass_filenames: false
