name: Push Docker Image
description: Logs into an OCI registry, builds a Docker image, and and pushes it there
inputs:
  registry:
    required: true
    description: Registry where Docker image will be pushed
  repository:
    required: true
    description: Repository where Docker image will be stored
    default: ${{ github.repository }}
  username:
    required: true
    description: Private registry username
  password:
    required: true
    description: Private registry password
  platforms:
    required: true
    description: Docker image architectures to build/push
    default: linux/amd64,linux/arm64
outputs:
  version:
    description: Docker image version
    value: ${{ steps.meta.outputs.version }}
runs:
  using: composite
  steps:
    - id: git_tag
      name: Get the Git tag
      shell: bash
      run: |
         echo "VERSION_BUILDARG=$(git describe --tags --always)" >> $GITHUB_ENV
    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - id: meta
      name: Extract Docker metadata
      uses: docker/metadata-action@v5
      env:
        DOCKER_METADATA_PR_HEAD_SHA: "true"
      with:
        images: ${{ inputs.registry }}/${{ inputs.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    - name: Build and push Docker production image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ inputs.platforms }}
        build-args: |
          VERSION=${{ env.VERSION_BUILDARG }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Build and push Docker debug image
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile.debug
        platforms: ${{ inputs.platforms }}
        build-args: |
          VERSION=${{ env.VERSION_BUILDARG }}-debug
        push: true
        tags: ${{ steps.meta.outputs.tags }}-debug
        labels: ${{ steps.meta.outputs.labels }}
