name: 'Docker Build and Push to Multiple Registries'
description: 'Builds and pushes Docker images to both GitHub Container Registry and Quay.io'
inputs:
  registry_gh:
    description: 'GitHub Container Registry URL'
    required: true
  username_gh:
    description: 'GitHub username or organization'
    required: true
  password_gh:
    description: 'GitHub token or password'
    required: true
  repository_gh:
    description: 'GitHub repository name'
    required: true
  registry_quay:
    description: 'Quay.io Registry URL'
    required: true
  username_quay:
    description: 'Quay.io username or organization'
    required: true
  password_quay:
    description: 'Quay.io token or password'
    required: true
  repository_quay:
    description: 'Quay.io repository name'
    required: true
  platforms:
    description: 'Build platforms (e.g., linux/amd64,linux/arm64)'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  suffix:
    description: 'add -debug suffix or not'
    required: false
    default: ''
outputs:
  version:
    description: 'Docker image version'
    value: ${{ steps.meta.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Get the Git tag
      shell: bash
      run: |
        echo "VERSION_BUILDARG=$(git describe --tags --always)" >> "${GITHUB_ENV}}"
    - name: Log in to the GHCR registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry_gh }}
        username: ${{ inputs.username_gh }}
        password: ${{ inputs.password_gh }}
    - name: Login to Quay.io registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry_quay }}
        username: ${{ inputs.username_quay }}
        password: ${{ inputs.password_quay }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      env:
        DOCKER_METADATA_PR_HEAD_SHA: "true"
      with:
        images: |
          name=${{ inputs.registry_quay }}/domino/${{ inputs.repository_quay }}
          name=${{ inputs.registry_gh }}/dominodatalab/hephaestus
        tags: |
          type=ref,event=branch, suffix=${{ inputs.suffix }}
          type=ref,event=pr,suffix=${{ inputs.suffix }}
          type=semver,pattern={{version}},suffix=${{ inputs.suffix }}
          type=semver,pattern={{major}}.{{minor}}, suffix=${{ inputs.suffix }}
          type=sha
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platforms }}
        file: ${{ inputs.dockerfile }}
        build-args: |
          VERSION=${{ env.VERSION_BUILDARG }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          type=gha, scope=${{ inputs.dockerfile }}
          ghcr.io/dominodatalab/dominodatalab/hephaestus${{ inputs.suffix }}:buildcache
        cache-to: |-
          type=gha, scope=${{ inputs.dockerfile }},mode=max
          ghcr.io/dominodatalab/dominodatalab/hephaestus${{ inputs.suffix }}:buildcache