name: Cloud Image Building
description: Run functional test suite against a specified cloud provider
inputs:
  verbose:
    description: Enable debug logging when running tests
    default: "false"
  github_token:
    description: GitHub token provided by workflow or PAT
    required: true
  target:
    description: Target cloud-provided Kubernetes (e.g. aks, eks, gke)
    required: true
runs:
  using: composite
  steps:
    - name: Checkout pull request
      if: github.event_name != 'pull_request'
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: gh pr checkout ${{ github.event.issue.number }}
      shell: bash

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: test/functional/go.mod
        cache-dependency-path: test/functional/go.sum

    - id: go-cache-paths
      name: Gather Go cache paths
      run: |
        echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Run tests
      env:
        VERBOSE_TESTING: ${{ inputs.verbose }}
      run: |
        export MANAGER_IMAGE_TAG=sha-$(git rev-parse --short HEAD)
        cd test/functional
        go test -v -timeout 0 -tags functional,${{ inputs.target }}
      shell: bash

    - name: Save testenv files
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: testenv-${{ inputs.target }}
        path: |
          test/functional/testenv
          !test/functional/testenv/**/.terraform/
