{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "hephaestus.webhook.service" .}}
  labels:
    {{- include "hephaestus.controller.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hephaestus.controller.labels.matchLabels" . | nindent 6 }}
  mtls:
    mode: UNSET
  portLevelMtls:
    {{ .Values.controller.manager.webhookPort }}:
      mode: PERMISSIVE
{{- end }}
