apiVersion: v1
kind: Service
metadata:
  name: {{ include "hephaestus.webhook.service" . }}
  labels:
    {{- include "hephaestus.controller.labels.standard" . | nindent 4 }}
spec:
  ports:
    - name: tcp-webhook
      port: 443
      targetPort: webhooks
  selector:
    {{- include "hephaestus.controller.labels.matchLabels" . | nindent 4 }}
