apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hephaestus.rbac.managerName" . }}
  labels:
    {{- include "hephaestus.controller.labels.standard" . | nindent 4 }}
rules:
  - apiGroups:
      - forge.dominodatalab.com
    resources:
      - containerimagebuilds
    verbs:
      - patch
      - list
      - watch
  - apiGroups:
      - forge.dominodatalab.com
    resources:
      - containerimagebuilds/status
    verbs:
      - patch
  - apiGroups:
      - hephaestus.dominodatalab.com
    resources:
      - imagebuilds
    verbs:
      - create

  - apiGroups:
      - hephaestus.dominodatalab.com
    resources:
      - imagebuilds
      - imagecaches
    verbs:
      - get
      - patch
      - list
      - watch
  - apiGroups:
      - hephaestus.dominodatalab.com
    resources:
      - imagebuilds/status
      - imagecaches/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - endpoints
      - secrets
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - watch
      - patch
  {{- if or (include "hephaestus.pspRequired" .) (include "hephaestus.istioWithoutCNI" .) }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
  {{- end }}
