apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hephaestus.rbac.managerName" . }}
  labels:
    {{- include "hephaestus.controller.labels.standard" . | nindent 4 }}
rules:
  - apiGroups:
      - forge.dominodatalab.com
    resources:
      - containerimagebuilds
    verbs:
      - patch
      - list
      - watch
  - apiGroups:
      - forge.dominodatalab.com
    resources:
      - containerimagebuilds/status
    verbs:
      - patch
  - apiGroups:
      - hephaestus.dominodatalab.com
    resources:
      - imagebuilds
    verbs:
      - create
      - delete
  - apiGroups:
      - hephaestus.dominodatalab.com
    resources:
      - imagebuilds
      - imagecaches
    verbs:
      - get
      - patch
      - list
      - watch
  - apiGroups:
      - hephaestus.dominodatalab.com
    resources:
      - imagebuildmessages
    verbs:
      - create
      - patch
      - list
      - watch
  - apiGroups:
      - hephaestus.dominodatalab.com
    resources:
      - imagebuilds/status
      - imagebuildmessages/status
      - imagecaches/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets/scale
    verbs:
      - update
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
  {{- if include "hephaestus.pspRequired" . }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "hephaestus.manager.name" . }}
    verbs:
      - use
  {{- end }}
