apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hephaestus.configSecretName" . }}
  labels:
    {{- include "hephaestus.controller.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    buildkit:
      namespace: {{ .Release.Namespace }}
      daemonPort: {{ .Values.buildkit.service.port }}
      serviceName: {{ include "hephaestus.buildkit.fullname" . }}
      statefulSetName: {{ include "hephaestus.buildkit.fullname" . }}
      {{- if .Values.buildkit.mtls.enabled }}
      mtls:
        caCertPath: /etc/hephaestus/x509/ca.crt
        certPath: /etc/hephaestus/x509/tls.crt
        keyPath: /etc/hephaestus/x509/tls.key
      {{- end }}
      podLabels:
        {{- include "hephaestus.buildkit.labels.matchLabels" . | nindent 8 }}
      {{- with .Values.controller.poolSyncWaitTime }}
      poolSyncWaitTime: {{ . | quote }}
      {{- end }}
      {{- with .Values.controller.poolMaxIdleTime }}
      poolMaxIdleTime: {{ . | quote }}
      {{- end }}
      {{- with .Values.controller.secrets }}
      secrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.controller }}
    imageBuildMaxConcurrency: {{ .imageBuildMaxConcurrency }}
    manager:
      healthProbeAddr: ":{{ .healthProbePort }}"
      metricsAddr: ":{{ .metricsPort }}"
      webhookPort: {{ .webhookPort }}
      watchNamespaces: {{ .watchNamespaces }}
      enabledLeaderElection: {{ gt (.replicaCount | int) 1 }}
    logging:
      stacktraceLevel: {{ .logging.stacktraceLevel | quote }}
      container:
        encoder: {{ .logging.container.encoding | quote }}
        level: {{ .logging.container.level | quote }}
      logfile:
        enabled: {{ $.Values.logProcessor.enabled }}
        filepath: {{ include "hephaestus.logfilePath" $ | quote }}
        level: {{ .logging.logfile.level | quote }}
    messaging:
      {{- with .messaging }}
      enabled: {{ .enabled }}
      amqp:
        url: {{ .amqp.url | quote }}
        exchange: {{ .amqp.exchange | quote }}
        queue: {{ .amqp.queue | quote }}
      kafka: {{ .kafka | toYaml }}
      {{- end }}
    {{- end }}
  {{- if .Values.logProcessor.enabled }}
  vector.yaml: |
    sources:
      hephaestus_output:
        type: file
        include:
          - {{ include "hephaestus.logfilePath" . }}
    {{- with .Values.logProcessor.config.transforms }}
    transforms:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.logProcessor.config.sinks }}
    sinks:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
